# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\worksrc\PythonCode\PyPlayerSelf\PlayerWeight.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FreePlayer(object):
    def setupUi(self, FreePlayer):
        FreePlayer.setObjectName("FreePlayer")
        FreePlayer.resize(415, 92)
        FreePlayer.setStyleSheet("background: rgb(170, 170, 127);")
        self.PyPlayer = QtWidgets.QWidget(FreePlayer)
        self.PyPlayer.setObjectName("PyPlayer")
        self.btnPlay = QtWidgets.QPushButton(self.PyPlayer)
        self.btnPlay.setGeometry(QtCore.QRect(0, 10, 41, 31))
        self.btnPlay.setObjectName("btnPlay")
        self.lineEdit = QtWidgets.QLineEdit(self.PyPlayer)
        self.lineEdit.setGeometry(QtCore.QRect(120, 10, 291, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.btnDel = QtWidgets.QPushButton(self.PyPlayer)
        self.btnDel.setGeometry(QtCore.QRect(0, 50, 41, 31))
        self.btnDel.setObjectName("btnDel")
        self.btnPop = QtWidgets.QPushButton(self.PyPlayer)
        self.btnPop.setGeometry(QtCore.QRect(120, 50, 41, 31))
        self.btnPop.setObjectName("btnPop")
        self.btnBlues = QtWidgets.QPushButton(self.PyPlayer)
        self.btnBlues.setGeometry(QtCore.QRect(170, 50, 41, 31))
        self.btnBlues.setObjectName("btnBlues")
        self.btnCountry = QtWidgets.QPushButton(self.PyPlayer)
        self.btnCountry.setGeometry(QtCore.QRect(220, 50, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.btnCountry.setFont(font)
        self.btnCountry.setIconSize(QtCore.QSize(16, 16))
        self.btnCountry.setObjectName("btnCountry")
        self.btnMetal = QtWidgets.QPushButton(self.PyPlayer)
        self.btnMetal.setGeometry(QtCore.QRect(270, 50, 41, 31))
        self.btnMetal.setObjectName("btnMetal")
        self.btnPunk = QtWidgets.QPushButton(self.PyPlayer)
        self.btnPunk.setGeometry(QtCore.QRect(320, 50, 41, 31))
        self.btnPunk.setObjectName("btnPunk")
        self.btnHard = QtWidgets.QPushButton(self.PyPlayer)
        self.btnHard.setGeometry(QtCore.QRect(370, 50, 41, 31))
        self.btnHard.setObjectName("btnHard")
        self.btnPause = QtWidgets.QPushButton(self.PyPlayer)
        self.btnPause.setGeometry(QtCore.QRect(60, 10, 51, 31))
        self.btnPause.setObjectName("btnPause")
        self.btnPre = QtWidgets.QPushButton(self.PyPlayer)
        self.btnPre.setGeometry(QtCore.QRect(60, 50, 21, 31))
        self.btnPre.setObjectName("btnPre")
        self.btnNext = QtWidgets.QPushButton(self.PyPlayer)
        self.btnNext.setGeometry(QtCore.QRect(90, 50, 21, 31))
        self.btnNext.setObjectName("btnNext")
        FreePlayer.setCentralWidget(self.PyPlayer)

        self.retranslateUi(FreePlayer)
        QtCore.QMetaObject.connectSlotsByName(FreePlayer)

    def retranslateUi(self, FreePlayer):
        _translate = QtCore.QCoreApplication.translate
        FreePlayer.setWindowTitle(_translate("FreePlayer", "MainWindow"))
        self.btnPlay.setText(_translate("FreePlayer", ">"))
        self.btnDel.setText(_translate("FreePlayer", "DEL"))
        self.btnPop.setText(_translate("FreePlayer", "Pop"))
        self.btnBlues.setText(_translate("FreePlayer", "Blues"))
        self.btnCountry.setText(_translate("FreePlayer", "Country"))
        self.btnMetal.setText(_translate("FreePlayer", "Metal"))
        self.btnPunk.setText(_translate("FreePlayer", "Punk"))
        self.btnHard.setText(_translate("FreePlayer", "Hard R"))
        self.btnPause.setText(_translate("FreePlayer", "||"))
        self.btnPre.setText(_translate("FreePlayer", "<<"))
        self.btnNext.setText(_translate("FreePlayer", ">>"))
