# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Project\PyQtGui\DelSamFilesPrj\doubleFloder.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_doubleForm(object):
    def setupUi(self, doubleForm):
        doubleForm.setObjectName("doubleForm")
        doubleForm.resize(1230, 847)
        doubleForm.setStyleSheet("background-color:#808A87;")
        self.btnFileA = QtWidgets.QPushButton(doubleForm)
        self.btnFileA.setGeometry(QtCore.QRect(40, 30, 131, 51))
        self.btnFileA.setStyleSheet("background-color: #F0FFFF;\n"
"font: 12pt \"仿宋\";")
        self.btnFileA.setObjectName("btnFileA")
        self.btnFileB = QtWidgets.QPushButton(doubleForm)
        self.btnFileB.setGeometry(QtCore.QRect(40, 120, 131, 51))
        self.btnFileB.setStyleSheet("background-color: #F0FFFF;\n"
"font: 12pt \"仿宋\";")
        self.btnFileB.setObjectName("btnFileB")
        self.edtFileA = QtWidgets.QTextEdit(doubleForm)
        self.edtFileA.setGeometry(QtCore.QRect(230, 30, 901, 51))
        self.edtFileA.setStyleSheet("background-color: rgb(183, 209, 255);\n"
"font: 16pt \"宋体\";")
        self.edtFileA.setObjectName("edtFileA")
        self.edtFileB = QtWidgets.QTextEdit(doubleForm)
        self.edtFileB.setGeometry(QtCore.QRect(230, 120, 901, 51))
        self.edtFileB.setStyleSheet("background-color: rgb(183, 209, 255);\n"
"font: 16pt \"宋体\";")
        self.edtFileB.setObjectName("edtFileB")
        self.btnDetect = QtWidgets.QPushButton(doubleForm)
        self.btnDetect.setGeometry(QtCore.QRect(40, 200, 131, 51))
        self.btnDetect.setStyleSheet("background-color: #00FF00;\n"
"font: 12pt \"仿宋\";")
        self.btnDetect.setObjectName("btnDetect")
        self.btnDelSel = QtWidgets.QPushButton(doubleForm)
        self.btnDelSel.setGeometry(QtCore.QRect(1000, 200, 131, 51))
        self.btnDelSel.setStyleSheet("background-color: #FF0000;\n"
"font: 12pt \"仿宋\";")
        self.btnDelSel.setObjectName("btnDelSel")
        self.btnDelA = QtWidgets.QPushButton(doubleForm)
        self.btnDelA.setGeometry(QtCore.QRect(330, 200, 131, 51))
        self.btnDelA.setStyleSheet("background-color:#FFE384;\n"
"font: 12pt \"仿宋\";")
        self.btnDelA.setObjectName("btnDelA")
        self.btnDelB = QtWidgets.QPushButton(doubleForm)
        self.btnDelB.setGeometry(QtCore.QRect(670, 200, 131, 51))
        self.btnDelB.setStyleSheet("background-color: #B0E0E6;\n"
"font: 12pt \"仿宋\";")
        self.btnDelB.setObjectName("btnDelB")
        self.tvShow = QtWidgets.QTableView(doubleForm)
        self.tvShow.setGeometry(QtCore.QRect(40, 290, 1101, 521))
        self.tvShow.setStyleSheet("background-color: rgb(153, 153, 115);")
        self.tvShow.setObjectName("tvShow")

        self.retranslateUi(doubleForm)
        QtCore.QMetaObject.connectSlotsByName(doubleForm)

    def retranslateUi(self, doubleForm):
        _translate = QtCore.QCoreApplication.translate
        doubleForm.setWindowTitle(_translate("doubleForm", "Form"))
        self.btnFileA.setText(_translate("doubleForm", "Select File A"))
        self.btnFileB.setText(_translate("doubleForm", "Select File B"))
        self.btnDetect.setText(_translate("doubleForm", "Detect"))
        self.btnDelSel.setText(_translate("doubleForm", "删除选中"))
        self.btnDelA.setText(_translate("doubleForm", "Delte In A"))
        self.btnDelB.setText(_translate("doubleForm", "Delete In B"))
