# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Project\PyQtGui\DelSamFilesPrj\mainform.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Ui_doubleFloder import Ui_doubleForm
from Ui_signalFloder import Ui_signalForm

class Ui_MainForm(object):
    def btnSignalClick(self):
        self.mForm.close()
        uiSignalForm = Ui_signalForm()
        DialogWin = QtWidgets.QDialog()
        uiSignalForm.setupUi(DialogWin)
        DialogWin.show()
        DialogWin.exec_()
    def btnDoubleClick(self):
        self.mForm.close()
        uiDoubleForm = Ui_doubleForm()
        DialogWin = QtWidgets.QDialog()
        uiDoubleForm.setupUi(DialogWin)
        DialogWin.show()
        DialogWin.exec_()
    def setupUi(self, MainForm):
        self.mForm = MainForm
        MainForm.setObjectName("MainForm")
        MainForm.resize(720, 262)
        MainForm.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.btnSignal = QtWidgets.QPushButton(MainForm)
        self.btnSignal.setGeometry(QtCore.QRect(70, 80, 231, 91))
        self.btnSignal.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"font: 26pt \"Segoe Script\";")
        self.btnSignal.setObjectName("btnSignal")
        self.btnDouble = QtWidgets.QPushButton(MainForm)
        self.btnDouble.setGeometry(QtCore.QRect(370, 80, 251, 91))
        self.btnDouble.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"font: 26pt \"Segoe Script\";")
        self.btnDouble.setObjectName("btnDouble")
        
        self.btnSignal.clicked.connect(self.btnSignalClick)
        self.btnDouble.clicked.connect(self.btnDoubleClick)
    
        self.retranslateUi(MainForm)
        QtCore.QMetaObject.connectSlotsByName(MainForm)

    def retranslateUi(self, MainForm):
        _translate = QtCore.QCoreApplication.translate
        MainForm.setWindowTitle(_translate("MainForm", "Form"))
        self.btnSignal.setText(_translate("MainForm", "单文件夹"))
        self.btnDouble.setText(_translate("MainForm", "双文件夹"))
