# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Project\PyQtGui\DelSamFilesPrj\signalFloder.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from collections import Counter
from PyQt5.QtWidgets import QApplication, QWidget, QPushButton, QMessageBox
from PyQt5.QtCore import *
from PyQt5.QtGui import *
import os

class Ui_signalForm(object):

    def getFilesInfos(self, dirName):
        dictInfo = {}
        for root, dirs, files in os.walk(dirName, topdown=False):
            for file in files:
                absFilePath = root + os.sep + file
                fSize = os.path.getsize(absFilePath)
                
                dictInfo[absFilePath] = fSize

        return dictInfo

    def getSameFiles(self, dictInfo):
        listValue = []
        for value in dictInfo.values():
            listValue.append(value)
        listDict = dict(Counter(listValue))
        listSame = [key for key, value in listDict.items() if value > 1]
        return listSame

    def getSameDeatils(self, listSame, dictInfo):
        listSameFiles = []
        for magicNum in listSame:
            listMagicFile = []
            for key in dictInfo.keys():
                value = dictInfo[key]
                if value == magicNum:
                    listMagicFile.append(key)
                    
            listSameFiles.append(listMagicFile)
        return listSameFiles
    
    def btnDelAClick(self):
        for filePair in self.sameFiles:
            if os.path.exists(filePair[0]):
                os.remove(filePair[0])
    
    def btnDelAutoClick(self):
        self.model.setData(self.index, "")
        if os.path.exists(self.curSelDir):
            os.remove(self.curSelDir)

    def tbvSelectClick(self, index):
        self.index = index
        curSelDir = self.model.data(index)
        self.curSelDir = curSelDir

    def btnFileClick(self):
        self.fileDir = QtWidgets.QFileDialog.getExistingDirectory()
        self.edtFileA.setText(self.fileDir)
        self.edtFileA.setAlignment(Qt.AlignCenter)

    def btnDetectClick(self):
        dictInfo = self.getFilesInfos(self.fileDir)
        listSame = self.getSameFiles(dictInfo)
        samefileList = self.getSameDeatils(listSame, dictInfo)
        self.sameFiles = samefileList
        model = QStandardItemModel(len(samefileList), 3)
        for index in range(len(samefileList)):
            samePair = samefileList[index]
            row = 0
            for same in samePair:
                pathItem = QStandardItem("%s"%(same))
                model.setItem(index, row, pathItem)
                row = row + 1
                if row >3:
                    break
        self.tvLeft.setModel(model)
        self.model = model
        self.tvLeft.setColumnWidth(0, 450)
        self.tvLeft.setColumnWidth(1, 450)
    
    def setupUi(self, signalForm):
        signalForm.setObjectName("signalForm")
        signalForm.resize(1112, 833)
        signalForm.setStyleSheet("background-color: rgb(189, 154, 200);")
        self.tvLeft = QtWidgets.QTableView(signalForm)
        self.tvLeft.setGeometry(QtCore.QRect(110, 240, 901, 541))
        self.tvLeft.setStyleSheet("background-color: rgb(244, 213, 255);")
        self.tvLeft.setObjectName("tvLeft")
        self.btnDelSel = QtWidgets.QPushButton(signalForm)
        self.btnDelSel.setGeometry(QtCore.QRect(490, 130, 131, 51))
        self.btnDelSel.setStyleSheet("background-color: #FF0000;\n"
"font: 12pt \"仿宋\";")
        self.btnDelSel.setObjectName("btnDelSel")
        self.edtFileA = QtWidgets.QTextEdit(signalForm)
        self.edtFileA.setGeometry(QtCore.QRect(350, 30, 651, 51))
        self.edtFileA.setStyleSheet("background-color: rgb(183, 209, 255);\n"
"font: 16pt \"宋体\";")
        self.edtFileA.setObjectName("edtFileA")
        self.btnDelA = QtWidgets.QPushButton(signalForm)
        self.btnDelA.setGeometry(QtCore.QRect(870, 130, 131, 51))
        self.btnDelA.setStyleSheet("background-color:#FFE384;\n"
"font: 12pt \"仿宋\";")
        self.btnDelA.setObjectName("btnDelA")
        self.btnFile = QtWidgets.QPushButton(signalForm)
        self.btnFile.setGeometry(QtCore.QRect(120, 30, 131, 51))
        self.btnFile.setStyleSheet("background-color: #F0FFFF;\n"
"font: 12pt \"仿宋\";")
        self.btnFile.setObjectName("btnFile")
        self.btnDetect = QtWidgets.QPushButton(signalForm)
        self.btnDetect.setGeometry(QtCore.QRect(120, 130, 131, 51))
        self.btnDetect.setStyleSheet("background-color: #00FF00;\n"
"font: 12pt \"仿宋\";")
        self.btnDetect.setObjectName("btnDetect")

        self.btnFile.clicked.connect(self.btnFileClick)
        self.btnDetect.clicked.connect(self.btnDetectClick)
        self.btnDelA.clicked.connect(self.btnDelAClick)
        self.btnDelSel.clicked.connect(self.btnDelAutoClick)
        self.tvLeft.clicked.connect(self.tbvSelectClick)

        self.retranslateUi(signalForm)
        QtCore.QMetaObject.connectSlotsByName(signalForm)

    def retranslateUi(self, signalForm):
        _translate = QtCore.QCoreApplication.translate
        signalForm.setWindowTitle(_translate("signalForm", "Form"))
        self.btnDelSel.setText(_translate("signalForm", "删除选中"))
        self.btnDelA.setText(_translate("signalForm", "删除所有多余"))
        self.btnFile.setText(_translate("signalForm", "Select File"))
        self.btnDetect.setText(_translate("signalForm", "检测"))
