# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Project\PyQtGui\AESTools\DesRunning.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from cryptography.fernet import Fernet
import os
import shutil
import datetime

class Ui_DesRun(object):
    def getStrNow(self):
        now_time = datetime.datetime.now()
        trTime = datetime.datetime.now().strftime('%Y_%m_%d_%H_%M_%S')
        return trTime
    def loadKey(self):
        self.keyPath = QtWidgets.QFileDialog.getOpenFileName(None, "Sel key",  "", "All Files (*);;Text Files (*.key)")[0]
        self.edtKey.setText(self.keyPath)
        self.edtKey.setAlignment(Qt.AlignCenter)
        self.edtKey.setStyleSheet("background-color: rgb(128, 161, 166);\nfont: 12pt \"新宋体\";")
       
    def loadFile(self):
        self.filePath = QtWidgets.QFileDialog.getOpenFileName(None, "Sel File",  "", "All Files (*)")[0]
        self.edtFile.setText(self.filePath)
        self.edtFile.setAlignment(Qt.AlignCenter)
        self.edtFile.setStyleSheet("background-color: rgb(128, 161, 166);\nfont: 12pt \"新宋体\";")
        self.btnDes.setEnabled(True)

    def desRun(self):
        curDir = os.getcwd()
        desDir = os.path.dirname(curDir) + os.sep + "DesOut"
        curTimeStr = self.getStrNow()
        outKey = desDir + os.sep + "key_" + curTimeStr + ".key"
        outFile = desDir + os.sep + "des_" +  curTimeStr +  ".md"
        if not os.path.exists(desDir):
            os.makedirs(desDir)

        keyContent = open(self.keyPath, "rb").read()
        f = Fernet(keyContent)
        with open(self.filePath, "rb") as file:
            encrypted_data = file.read()
        decrypted_data = f.decrypt(encrypted_data)
        with open(outFile, "wb") as file:
            file.write(decrypted_data)
            outFileName = curTimeStr +  ".md"
            self.lblSmile.setText("> " + outFileName)
            self.lblSmile.setStyleSheet("background-color: rgb(110, 200, 197);\nfont: 10pt \"新宋体\";")
          
    def setupUi(self, DesRun):
        DesRun.setObjectName("DesRun")
        DesRun.resize(694, 459)
        DesRun.setStyleSheet("background-color: rgb(155, 163, 214);")
        self.btnKey = QtWidgets.QPushButton(DesRun)
        self.btnKey.setGeometry(QtCore.QRect(70, 80, 151, 61))
        self.btnKey.setStyleSheet("background-color: rgb(97, 205, 255);\n"
"font: 20pt \"新宋体\";")
        self.btnKey.setObjectName("btnKey")
        self.edtKey = QtWidgets.QTextEdit(DesRun)
        self.edtKey.setGeometry(QtCore.QRect(280, 80, 361, 61))
        self.edtKey.setStyleSheet("background-color: rgb(128, 161, 166);")
        self.edtKey.setObjectName("edtKey")
        self.btnFile = QtWidgets.QPushButton(DesRun)
        self.btnFile.setGeometry(QtCore.QRect(70, 190, 151, 61))
        self.btnFile.setStyleSheet("background-color: rgb(97, 205, 255);\n"
"font: 20pt \"新宋体\";")
        self.btnFile.setObjectName("btnFile")
        self.edtFile = QtWidgets.QTextEdit(DesRun)
        self.edtFile.setGeometry(QtCore.QRect(280, 190, 361, 61))
        self.edtFile.setStyleSheet("background-color: rgb(128, 161, 166);")
        self.edtFile.setObjectName("edtFile")
        self.btnDes = QtWidgets.QPushButton(DesRun)
        self.btnDes.setGeometry(QtCore.QRect(70, 330, 151, 61))
        self.btnDes.setStyleSheet("background-color: rgb(97, 205, 255);\n"
"font: 22pt \"新宋体\";")
        self.btnDes.setObjectName("btnDes")
        self.lblSmile = QtWidgets.QLabel(DesRun)
        self.lblSmile.setGeometry(QtCore.QRect(440, 330, 201, 61))
        self.lblSmile.setStyleSheet("background-color: rgb(110, 200, 197);\n"
"font: 20pt \"新宋体\";")
        self.lblSmile.setObjectName("lblSmile")


        self.btnKey.clicked.connect(self.loadKey)
        self.btnFile.clicked.connect(self.loadFile)
        self.btnDes.clicked.connect(self.desRun)
        self.btnDes.setDisabled(True)

        self.retranslateUi(DesRun)
        QtCore.QMetaObject.connectSlotsByName(DesRun)

    def retranslateUi(self, DesRun):
        _translate = QtCore.QCoreApplication.translate
        DesRun.setWindowTitle(_translate("DesRun", "Form"))
        self.btnKey.setText(_translate("DesRun", "选择KEY"))
        self.btnFile.setText(_translate("DesRun", "选择FILE"))
        self.btnDes.setText(_translate("DesRun", "解"))
        self.lblSmile.setText(_translate("DesRun", "<html><head/><body><p align=\"center\">Smile</p></body></html>"))
