# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\SyncDiskProj\SyncDiskFiles.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(998, 597)
        Form.setStyleSheet("background-color:#808A87;")
        self.btnFileA = QtWidgets.QPushButton(Form)
        self.btnFileA.setGeometry(QtCore.QRect(40, 30, 131, 51))
        self.btnFileA.setStyleSheet("background-color: #F0FFFF;\n"
"font: 12pt \"仿宋\";")
        self.btnFileA.setObjectName("btnFileA")
        self.btnFileB = QtWidgets.QPushButton(Form)
        self.btnFileB.setGeometry(QtCore.QRect(40, 120, 131, 51))
        self.btnFileB.setStyleSheet("background-color: #F0FFFF;\n"
"font: 12pt \"仿宋\";")
        self.btnFileB.setObjectName("btnFileB")
        self.edtFileA = QtWidgets.QTextEdit(Form)
        self.edtFileA.setGeometry(QtCore.QRect(230, 30, 731, 51))
        self.edtFileA.setStyleSheet("background-color: rgb(183, 209, 255);\n"
"font: 16pt \"宋体\";")
        self.edtFileA.setObjectName("edtFileA")
        self.edtFileB = QtWidgets.QTextEdit(Form)
        self.edtFileB.setGeometry(QtCore.QRect(230, 120, 731, 51))
        self.edtFileB.setStyleSheet("background-color: rgb(183, 209, 255);\n"
"font: 16pt \"宋体\";")
        self.edtFileB.setObjectName("edtFileB")
        self.pdtInfo = QtWidgets.QPlainTextEdit(Form)
        self.pdtInfo.setGeometry(QtCore.QRect(40, 280, 921, 301))
        self.pdtInfo.setStyleSheet("background-color: rgb(210, 213, 255);")
        self.pdtInfo.setObjectName("pdtInfo")
        self.btnSyncBoth = QtWidgets.QPushButton(Form)
        self.btnSyncBoth.setGeometry(QtCore.QRect(40, 200, 131, 51))
        self.btnSyncBoth.setStyleSheet("background-color: #00FF00;\n"
"font: 12pt \"仿宋\";")
        self.btnSyncBoth.setObjectName("btnSyncBoth")
        self.btnStop = QtWidgets.QPushButton(Form)
        self.btnStop.setGeometry(QtCore.QRect(830, 200, 131, 51))
        self.btnStop.setStyleSheet("background-color: #FF0000;\n"
"font: 12pt \"仿宋\";")
        self.btnStop.setObjectName("btnStop")
        self.btnSyncAToB = QtWidgets.QPushButton(Form)
        self.btnSyncAToB.setGeometry(QtCore.QRect(290, 200, 131, 51))
        self.btnSyncAToB.setStyleSheet("background-color:#FFE384;\n"
"font: 12pt \"仿宋\";")
        self.btnSyncAToB.setObjectName("btnSyncAToB")
        self.btnSyncBToA = QtWidgets.QPushButton(Form)
        self.btnSyncBToA.setGeometry(QtCore.QRect(560, 200, 131, 51))
        self.btnSyncBToA.setStyleSheet("background-color: #B0E0E6;\n"
"font: 12pt \"仿宋\";")
        self.btnSyncBToA.setObjectName("btnSyncBToA")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnFileA.setText(_translate("Form", "Select File A"))
        self.btnFileB.setText(_translate("Form", "Select File B"))
        self.btnSyncBoth.setText(_translate("Form", "Sync Both"))
        self.btnStop.setText(_translate("Form", "Stop Sync"))
        self.btnSyncAToB.setText(_translate("Form", "Sync A To B"))
        self.btnSyncBToA.setText(_translate("Form", "Sync B to A"))
