# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\worksrc\PythonCode\NeusoftProject\AdbDebuging\QtAdbLogPlugin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QtAdbLogPlugin(object):
    def setupUi(self, QtAdbLogPlugin):
        QtAdbLogPlugin.setObjectName("QtAdbLogPlugin")
        QtAdbLogPlugin.resize(869, 61)
        QtAdbLogPlugin.setAutoFillBackground(False)
        QtAdbLogPlugin.setStyleSheet("background-color: rgb(145, 145, 216);")
        self.centralwidget = QtWidgets.QWidget(QtAdbLogPlugin)
        self.centralwidget.setObjectName("centralwidget")
        self.lblStatus = QtWidgets.QLabel(self.centralwidget)
        self.lblStatus.setGeometry(QtCore.QRect(690, 10, 81, 41))
        self.lblStatus.setStyleSheet("background-color: rgb(163, 170, 142);")
        self.lblStatus.setText("")
        self.lblStatus.setObjectName("lblStatus")
        self.ldtPath = QtWidgets.QLineEdit(self.centralwidget)
        self.ldtPath.setGeometry(QtCore.QRect(100, 10, 371, 41))
        self.ldtPath.setObjectName("ldtPath")
        self.btnSelFod = QtWidgets.QPushButton(self.centralwidget)
        self.btnSelFod.setGeometry(QtCore.QRect(480, 10, 71, 41))
        self.btnSelFod.setObjectName("btnSelFod")
        self.btnKeyWord = QtWidgets.QPushButton(self.centralwidget)
        self.btnKeyWord.setGeometry(QtCore.QRect(590, 10, 71, 41))
        self.btnKeyWord.setObjectName("btnKeyWord")
        self.btnExit = QtWidgets.QPushButton(self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(780, 10, 81, 41))
        self.btnExit.setObjectName("btnExit")
        self.btnStart = QtWidgets.QPushButton(self.centralwidget)
        self.btnStart.setGeometry(QtCore.QRect(10, 10, 71, 41))
        self.btnStart.setObjectName("btnStart")
        QtAdbLogPlugin.setCentralWidget(self.centralwidget)

        self.retranslateUi(QtAdbLogPlugin)
        QtCore.QMetaObject.connectSlotsByName(QtAdbLogPlugin)

    def retranslateUi(self, QtAdbLogPlugin):
        _translate = QtCore.QCoreApplication.translate
        QtAdbLogPlugin.setWindowTitle(_translate("QtAdbLogPlugin", "MainWindow"))
        self.btnSelFod.setText(_translate("QtAdbLogPlugin", "Sel Folder"))
        self.btnKeyWord.setText(_translate("QtAdbLogPlugin", "SetCfg"))
        self.btnExit.setText(_translate("QtAdbLogPlugin", "EXIT"))
        self.btnStart.setText(_translate("QtAdbLogPlugin", "Start"))
