# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Project\PyQtGui\QmcNcmExpend\uglyformat.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(781, 642)
        Form.setStyleSheet("background-color: rgb(62, 170, 200);")
        self.btnDir = QtWidgets.QPushButton(Form)
        self.btnDir.setGeometry(QtCore.QRect(80, 110, 141, 51))
        self.btnDir.setStyleSheet("background-color: rgb(80, 185, 255);\n"
"font: 22pt \"Sitka Text\";")
        self.btnDir.setObjectName("btnDir")
        self.edtDir = QtWidgets.QTextEdit(Form)
        self.edtDir.setGeometry(QtCore.QRect(280, 110, 431, 51))
        self.edtDir.setStyleSheet("font: 22pt \"Kalam Light\";\n"
"background-color: rgb(117, 207, 255);")
        self.edtDir.setObjectName("edtDir")
        self.btnStart = QtWidgets.QPushButton(Form)
        self.btnStart.setGeometry(QtCore.QRect(80, 200, 141, 51))
        self.btnStart.setStyleSheet("background-color: rgb(80, 185, 255);\n"
"font: 22pt \"Sitka Text\";")
        self.btnStart.setObjectName("btnStart")
        self.btnDel = QtWidgets.QPushButton(Form)
        self.btnDel.setGeometry(QtCore.QRect(280, 200, 141, 51))
        self.btnDel.setStyleSheet("background-color: rgb(80, 185, 255);\n"
"font: 22pt \"Sitka Text\";")
        self.btnDel.setObjectName("btnDel")
        self.btnClear = QtWidgets.QPushButton(Form)
        self.btnClear.setGeometry(QtCore.QRect(570, 200, 141, 51))
        self.btnClear.setStyleSheet("background-color: rgb(80, 185, 255);\n"
"font: 22pt \"Sitka Text\";")
        self.btnClear.setObjectName("btnClear")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(110, 30, 381, 51))
        self.label.setStyleSheet("background-color: rgb(62, 150, 200);\n"
"font: 18pt \"Juice ITC\";")
        self.label.setObjectName("label")
        self.pdtShow = QtWidgets.QTextBrowser(Form)
        self.pdtShow.setGeometry(QtCore.QRect(80, 290, 631, 311))
        self.pdtShow.setStyleSheet("background-color: rgb(117, 207, 255);")
        self.pdtShow.setObjectName("pdtShow")
        self.btnQuit = QtWidgets.QPushButton(Form)
        self.btnQuit.setGeometry(QtCore.QRect(570, 30, 141, 51))
        self.btnQuit.setStyleSheet("background-color: rgb(80, 185, 255);\n"
"font: 22pt \"Sitka Text\";")
        self.btnQuit.setObjectName("btnQuit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnDir.setText(_translate("Form", "选择路径"))
        self.btnStart.setText(_translate("Form", "开始转换"))
        self.btnDel.setText(_translate("Form", "删除丑陋"))
        self.btnClear.setText(_translate("Form", "清空"))
        self.label.setText(_translate("Form", " 丑陋的网易云音乐ncm文件解码"))
        self.btnQuit.setText(_translate("Form", "退出"))
